---

- hosts: all
  become: true
  gather_facts: yes
  tasks:

  - name: install python3 and pip3
    apt:
      name: python3
      name: python3-pip

  - name: Using pip3 as default pip
    shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

  - name: Using python3 as default python
    shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 1      
 
  - name: install Java open-jdk
    apt:
      name: openjdk-11-jdk
  
  - name: install MariaDB
    apt:
      name: mariadb-server

  - name: start mariadb
    service:
      name: mariadb
      enabled: true

  - name: Message
    copy:
      content: "Ansible Manage Node by Zamora"
      dest: /etc/motd

  - name: User
    user:
      name: angelo
      state: present
      shell: /bin/bash
      comment: "PRELIM ZAMORA"
      createhome: yes
